modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/sneakylink/issues"
license = "MIT License"

[[mods]]
modId = "sneaky_link"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Full credits to Zym for the mod idea!"
displayURL = "https://github.com/davidjjung/sneakylink"
displayName = "Sneaky Link"
description = '''
    Players can pick up items from farther away while crouching.
    '''

[[dependencies.sneaky_link]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sneaky_link]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"